[package]
name = "adventurestothethird"
version = "0.1.0"
authors = ["Rasmus Rosengren <rsrp98@gmail.com>"]

[dependencies]
gfx = "0.17.1"
gl = "0.11.0"
glutin = "0.19.0"
gfx_window_glutin = "0.27.0"
